---
title: "FAQ"
# description: |
#   some faqs
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<center>
## When are we getting married? 
## October 24th, 2026
### Time until the wedding: 
<div id="countdown"></div>
<script src="js/countdown.js"></script>

 ::: 

## Where is the wedding going to be? 
### The ceremony will be at the church Sacré-Coeur at 381 Sherbourne St, Toronto, ON M4X 1K4, Canada.

 :::

## What should I wear? 
### Dress code is formal. Elegant and chic attire; think suits, full length dresses, dress shoes, heels or dressy flats. Please enjoy the opportunity to dress up and wear your nicest outfit! 

 :::

## I don't speak french and/or I'm not catholic can I still attend the ceremony? 
### The wedding mass will take place in a french catholic church. You do not need to be a francophone or a practicing catholic to attend. We simply ask that you come witness our union. You may participate to the best of your ability if you're confirmed in the church. Otherwise you are welcome to attend and respect this important tradition. We will provide guidance for the mass parts, and trilingual elements will be included. 

 :::

## Can I take photos or videos during the ceremony?
### No. We ask that all of our guests power off their devices and keep them out of view during the ceremony in the church. This will help our professional team of photographers to achieve the nicest unobstructed views of the ceremony. This will also allow you to enjoy the moment in your memories alongside of us. 

 :::

## Can I bring my beautiful children? 
### As much as we'd love to share our evening with your kiddos, we will be keeping this celebration to adults only. Thank you for understanding.

 :::

## What time should we arrive?
### Please be seated in the church by 2:15pm. We will have an organist playing music, and a ring warming tradition we wish to have you join in on before the ceremony begins.  

 :::

## Where should I park? 
### Please see the Schedule tab for parking information. the church provides some parking, there is on street parking, and the arts and letters club is only a short 5 minute uber or leisurely 15 minutes walk from the church! 


 :::

## How will we get to the reception after the mass?
### The mass should end approximately around 3:30pm, you will then have two hours to make your way to the reception at the arts and letter club. Bring a change of shoes and walk over, or take a short (5 minute) uber ride, or drive over if you drove to the church (do I hear carpool?). Enjoy the time! 

 :::

## I haven't been to Toronto before is it safe to walk around? 
### Toronto is extremely safe! In late fall it might be a little chilly, so make sure to dress for the weather and bring an outdoor layer. The area outside of the church can have a mixed crowd, specially at Allan's gardens. Stay aware and in a group and you shouldn't need to worry! Closer to the reception space is the notorious Sankofa square, lots of lights, people, and things to see. 
Fun fact: Monique worked at the Toronto Metropolitan University for a year after her undergrad!


 :::
 
## Do you have any restaurant recommendations or Recommendations for Toronto in General?
### Here are some suggestions! <a href="https://docs.google.com/document/d/133mRe0F14Qju6gMqyXFNaj32oiTU5WLvLHH79OkIhrQ/edit?usp=sharing"> Monique's guide to Toronto - click here </a> and if you're looking for another opinion for food. <a href="https://guide.michelin.com/us/en/ontario/toronto/restaurants"> Michelin Food Guide Toronto - click here </a>

 :::
 
## whom should I contact with additional questions? 
### moniqueandalejandro [ @ ] gmail [.com]

 ::: 

## Who designed and put together this beautiful website? 
### Monique put together this website, with thousands of questions for Alejandro's preferences. She would like to give a shoutout to Leslie Zhen for the template he provided! 


<br> <br> <br>

</center>