---
title: "Schedule"
# description: |
#   some info about the schedule
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

# Hotel Block
We recommend staying at the very conveniently located Chelsea hotel. Please use the following link to book your stay to enjoy the courtesy rate. The preferred rate is available until September 25th, 2026.
<a href="https://reservation.brilliantbylangham.com/?adult=1&arrive=2026-10-23&chain=10316&child=0&config=brilliant&currency=CAD&depart=2026-10-25&group=TMW102326&hotel=59052&level=hotel&locale=en-US&productcurrency=CAD&rooms=1&theme=brilliant" style="text-decoration: underline;"> Chelsea link - click here </a>
<br>


# Parking for the Ceremony

### If you are choosing to drive to the ceremony, the church Sacré-Coeur offers a small parking lot just east off of Sherbourne. If this lot is full, paid street parking is available along Sherbourne and Carlton. Please make sure you read the parking signs carefully and adhere to any local traffic laws.
### We ask that if you park in the church parking lot that you do not leave your car there after the ceremony. 

<br>

# Parking for the Reception

### If you are driving to the reception from the ceremony, the Arts and letters club does not offer parking, but there is a <a href= "https://lots.impark.com/imp?utm_source=google&utm_medium=maps&utm_content=0090021&utm_campaign=local_canada#details=9,21"> <u>Impark lot 21 </u> </a> <a href="https://www.google.com/maps/place/Entrance+to+Parking/@43.6577372,-79.3864742,17z/data=!4m10!1m2!2m1!1sparking!3m6!1s0x882b3500583afe81:0x43b28c9d9f786206!8m2!3d43.6583349!4d-79.383836!15sCgdwYXJraW5nkgELcGFya2luZ19sb3TgAQA!16s%2Fg%2F11xcj8l0bl?entry=ttu&g_ep=EgoyMDI2MDIwNC4wIKXMDSoKLDEwMDc5MjA2N0gBUAM%3D"> <u> parking garage </u> </a>, <a href="https://www.google.com/maps/place/Parking+clicknpark+Toronto+-+28+Edward+Street/@43.6577372,-79.3864742,17z/data=!4m10!1m2!2m1!1sparking!3m6!1s0x882b35c562eb0e95:0x5247459a38debc1b!8m2!3d43.6568781!4d-79.382603!15sCgdwYXJraW5nkgELcGFya2luZ19sb3TgAQA!16s%2Fg%2F11yp15z9xh?entry=ttu&g_ep=EgoyMDI2MDIwNC4wIKXMDSoKLDEwMDc5MjA2N0gBUAM%3D" >Click N Park </a>nearby, and <a href="https://www.google.com/maps/place/Chelsea+Hotel+Underground+Parking/@43.6577372,-79.3864742,17z/data=!3m1!5s0x882b34ca80aae5ef:0x83ae96c9de33b77!4m10!1m2!2m1!1sparking!3m6!1s0x882b34ca80eee79d:0xb3762746ebf7ae3f!8m2!3d43.6588565!4d-79.3828571!15sCgdwYXJraW5nWgkiB3BhcmtpbmeSAQtwYXJraW5nX2xvdJoBI0NoWkRTVWhOTUc5blMwVk5TQzB0VFc1T2JFeFlVazVuRUFF4AEA-gEECAAQQA!16s%2Fg%2F11tjbvjj52?entry=ttu&g_ep=EgoyMDI2MDIwNC4wIKXMDSoKLDEwMDc5MjA2N0gBUAM%3D">Chelse hotel parking <a>. Please note that we do not endorse these facilities or have any affiliations; these are simply suggestions. Please use your own wisdom and do what you think is best for you. 

<br>
<br>
<br>



# Day of Schedule

## Please arrive at the ceremony by 2:15pm <br>
### at la Paroisse du Sacré-Coeur, <a href="https://www.google.com/maps/place/Paroisse+du+Sacr%C3%A9-C%C5%93ur/@43.6635878,-79.3735006,19z/data=!3m1!4b1!4m6!3m5!1s0x89d4cb4ec2351e69:0x860acabd988b90ac!8m2!3d43.6635868!4d-79.3728569!16s%2Fg%2F1td2hx1k?entry=ttu&g_ep=EgoyMDI2MDIwNC4wIKXMDSoKLDEwMDc5MjA2N0gBUAM%3D"> 381 Sherbourne St, Toronto, ON M4X 1K4, Canada </a>. The ceremony will start promptly at 2:30pm. We understand that Toronto has notoriously bad traffic, please plan accordingly.The ceremony will be preceeded by a welcome music from <a href="https://www.youtube.com/@arangopmanuel"> Manuel Arango Perez </a> an organist from Montreal,  who will be playing from 2:00pm. 

## Reception: 
### Cocktail hour will start 15 minutes after the end of the ceremony. Our guests are welcome to make their way over to the <a href="https://maps.app.goo.gl/FqANmVY8eVogAACH8"> Arts and Letters club </a> at their leisure, feel free to be a tourist or wander around the neighbourhood (we recommend staying on or west of Yonge street). We ask that you are back at the reception by 5:30pm. The reception will end at midnight. 

# We ask that if you plan to enjoy any drinks that you please make the necessary arrangements to avoid driving. 


<!-- # Prelude -->
<!-- 12.7.24, 4pm - 4:30pm <br> -->
<!-- Domaine Pterion Vineyard & Winery <br> -->
<!-- <a href="https://www.google.com/maps/place/Domaine+Pterion+Vineyard+%26+Winery/@40.4891637,-75.5523934,17z/data=!3m1!4b1!4m6!3m5!1s0x89c42f7d4a436df7:0xb161dcc02088d873!8m2!3d40.4891596!4d-75.5498185!16s%2Fg%2F11rk5hjlkb?entry=ttu&g_ep=EgoyMDI0MDkwNC4wIKXMDSoASAFQAw%3D%3D">6501 St Peters Rd, Macungie, PA 18062</a> <br> -->
<!-- <br> <br> -->

<!-- # Ceremony -->
<!-- 12.7.24, 4:30pm - 5pm <br> -->
<!-- Domaine Pterion Vineyard & Winery <br> -->
<!-- <a href="https://www.google.com/maps/place/Domaine+Pterion+Vineyard+%26+Winery/@40.4891637,-75.5523934,17z/data=!3m1!4b1!4m6!3m5!1s0x89c42f7d4a436df7:0xb161dcc02088d873!8m2!3d40.4891596!4d-75.5498185!16s%2Fg%2F11rk5hjlkb?entry=ttu&g_ep=EgoyMDI0MDkwNC4wIKXMDSoASAFQAw%3D%3D">6501 St Peters Rd, Macungie, PA 18062</a> <br> -->
<!-- Cocktail Attire <br> -->
<!-- Please be seated by 4:25pm. Please silence or turn your phones off and keep them out of your hands. <br> -->
<!-- <br> <br> -->

<!-- # Cocktail Hour -->
<!-- 12.7.24, 5pm - 6pm <br> -->
<!-- Domaine Pterion Vineyard & Winery, Lower Level <br> -->
<!-- <a href="https://www.google.com/maps/place/Domaine+Pterion+Vineyard+%26+Winery/@40.4891637,-75.5523934,17z/data=!3m1!4b1!4m6!3m5!1s0x89c42f7d4a436df7:0xb161dcc02088d873!8m2!3d40.4891596!4d-75.5498185!16s%2Fg%2F11rk5hjlkb?entry=ttu&g_ep=EgoyMDI0MDkwNC4wIKXMDSoASAFQAw%3D%3D">6501 St Peters Rd, Macungie, PA 18062</a> <br> -->
<!-- <br> <br> -->




</center>