---
title: "My Adventure Buddy"
# description: |
#   our story
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
```

<center>
# How did you two meet?
**Alejandro:** We ended up playing on the same soccer team by chance. And we started talking during the social events of the team and then we really enjoyed each other's company to the point that we planned a trip to new york, shortly after we met. The rest is history.  
<br> <br>
**Monique:** I moved to Pittsburgh 'after' COVID in Spring 2021, in doing so I was trying to meet new people and make friends; I joined two different soccer teams. The second team was the friendlier of the two, we ended up all hanging after our games. Alejandro and I started talking and discovered that we shared a love of road trips. And that's where it all started. Nearly two years of friendship and adventures later, we chose to start our romantic relationship together, and here we are! 
<br> <br>

# How did the proposal happen?
**Alejandro:**  It happened during a trip because that's what we like to do together. 
I planned a surprise vacation to a special location for the two of us. I chose the place because it has both a beach element and a little chapel that looked very cute that I thought she would like. On the day of we woke up and I was very insistent on going to this beach and struggling to find reasons to go to the beach without raising suspicion. It was a little bit more walking than I thought once we got there. As we were approaching the chapel, I knew my sister was nearby and when we were in her camera's range, and front of the chapel's stairs, a fisherman caught a giant Octopus! Monique was very distracted by the Octopus, meanwhile I am trying to regain her attention and struggling to remember my speech. I started telling Monique that I love her a lot, that I really like her and that I have a very important question. And right before I said anything she asked, woah, what's going on. And then I got down on one knee and taking Monique's hand and asked her if she wanted to marry me. We both got emotional and...she said yes! 
Got up gave her a big hug and told her everything was being recorded. 
<br> <br>
**Monique:** On day 3 of a surprise birthday trip to Portugal Alejandro wanted to go explore a beautiful beach just south of Porto. It was a little chilly and still 8am so I was a little confused why we would rush to the beach before grabbing at least a little picnic. We arrived at a sleepy beach with gorgeous sand and rocks on the Atlantic ocean. Just off in the distance there happened to be a chapel, and I enthusiastically said that I would like to go see it! Upon approaching the chapel Alejandro got more nervous, and me more concerned for the very nervous Alejandro. Until he suddenly stopped. Right in front of the steps of the chapel on the rock, he asked me to marry him and I said yes!  ( I hadn't noticed that he stopped because a fisherman had just pulled AN ENTIRE OCTOPUS OUT OF THE OCEAN, and that was my first time seeing an entire live Octopus?!!).
<br> <br>

# Who asked whom out first? 
**Alejandro:** She asked me out first. We were in Toronto, and we wanted to go out to eat at Pai's. We sat at the bar and we started talking very honestly to each other. And next thing I remember is her saying that the ball was in my court. I wanted to make sure we knew what were signing up for, and it went way better than I thought. Look at us now!  
<br> <br>
**MT:** I'm not entirely sure. Looking back it's hard to tell when our 'first date' really was. 
<br> <br>

# What is our favorite trait about your partner?
**Alejandro:**  I really like how intentional and thoughtful she is about everything she does and says. 
<br> <br>
**Monique:** He's my kind of weird! More earnestly, he's incredibly thoughtful of, and committed to, the people he loves. 
<br> <br>

# Name one quirky trait/memory about your partner.
**Alejandro:** I think I have learned to recognize how she reacts to some of her pet peeves. I can now see those subtle reactions and that means a lot to me. It happens in many aspects of our relationship and lives, but it especially comes in handy when playing volleyball together!
<br> <br>
**Monique:** He's goofy...lol...There are so many memories, across so many continents. I think my favourite memory is of the feeling of coming home from work and spending a cozy evening together. A more specific memory is of driving home from a roadtrip at midnight still a few hours to go while blasting the radio singing our hearts out to Celine Dion!
<br> <br>

# What is our favorite travel memory together?
**Alejo:** We went to this beach in the outer banks, and we wanted to go stargazing. We drove there, and it was quiet, we were the only ones there. We just laid down on the beach being amazed by how beautiful the sky looked. 
<br> <br>
**Monique:** That time we never actually made it to inca inca beach in Colombia. In short, we spent an afternoon on a sailboat cruise, and got soaking wet from the rainstorm that had suddenly arrived; we absolutely froze. The goal of the sail boat was to arrive to inca inca, and we still yearn for the day we will arrive to see this mystical beach on the Colombian Atlantic coast.
<br> <br>

</center>